/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.penyewaanalatberat.view;

import com.penyewaanalatberat.model.AlatBerat;
import com.penyewaanalatberat.model.Bulldozer;
import com.penyewaanalatberat.model.Crane;
import com.penyewaanalatberat.model.Excavator;
import com.penyewaanalatberat.model.Penyewaan;
import com.penyewaanalatberat.service.AlatBeratService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oru
 */
public class MainMenu extends javax.swing.JFrame {

    private AlatBeratService alatBeratService = new AlatBeratService();
    
    private final List<Penyewaan> penyewaanList = new ArrayList<>();

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();

        labelPropTambahan.setVisible(false);
        jTxtTambahan.setVisible(false);
        jCmbJenis.setSelectedIndex(-1);

        refreshAlatTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelAlatBerat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlatBerat = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCmbJenis = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTxtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtHarga = new javax.swing.JTextField();
        labelPropTambahan = new javax.swing.JLabel();
        jTxtTambahan = new javax.swing.JTextField();
        jButtonTambahAlatBerat = new javax.swing.JButton();
        jButtonUpdateAlatBerat = new javax.swing.JButton();
        jButtonBatalAlatBerat = new javax.swing.JButton();
        jButtonDeleteAlatBerat = new javax.swing.JButton();
        jPanelPenyewaan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePenyewaan = new javax.swing.JTable();
        jTextCari = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jCmbPilihAlatBerat = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTxtNama1 = new javax.swing.JTextField();
        jTxtHarga1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonTambahPenyewaan = new javax.swing.JButton();
        jButtonUpdatePenyewaan = new javax.swing.JButton();
        jButtonBatalPenyewaan = new javax.swing.JButton();
        jButtonDeletePenyewaan = new javax.swing.JButton();
        jButtonCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sistem Manajemen Penyewaan Alat Berat");

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel1)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Home", jPanelHome);

        jTableAlatBerat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Jenis", "Nama", "Harga Sewa", "Spek"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableAlatBerat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlatBeratMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAlatBerat);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Jenis");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, -1, -1));

        jCmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulldozer", "Crane", "Excavator" }));
        jCmbJenis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbJenisItemStateChanged(evt);
            }
        });
        jPanel1.add(jCmbJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 0, 191, -1));

        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, -1, -1));
        jPanel1.add(jTxtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 34, 191, -1));

        jLabel4.setText("Harga Sewa");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, -1, -1));
        jPanel1.add(jTxtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 74, 191, -1));

        labelPropTambahan.setText("Property Tambahan");
        jPanel1.add(labelPropTambahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, -1, -1));
        jPanel1.add(jTxtTambahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 114, 191, -1));

        jButtonTambahAlatBerat.setText("Tambah");
        jButtonTambahAlatBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahAlatBeratActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTambahAlatBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jButtonUpdateAlatBerat.setText("Update");
        jButtonUpdateAlatBerat.setToolTipText("");
        jButtonUpdateAlatBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateAlatBeratActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdateAlatBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jButtonBatalAlatBerat.setText("Batal");
        jButtonBatalAlatBerat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBatalAlatBeratMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonBatalAlatBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        jButtonDeleteAlatBerat.setText("Delete");
        jButtonDeleteAlatBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteAlatBeratActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAlatBeratLayout = new javax.swing.GroupLayout(jPanelAlatBerat);
        jPanelAlatBerat.setLayout(jPanelAlatBeratLayout);
        jPanelAlatBeratLayout.setHorizontalGroup(
            jPanelAlatBeratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlatBeratLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanelAlatBeratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteAlatBerat))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelAlatBeratLayout.setVerticalGroup(
            jPanelAlatBeratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlatBeratLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelAlatBeratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAlatBeratLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeleteAlatBerat))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Alat Berat", jPanelAlatBerat);

        jTablePenyewaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Penyewa", "Alat Berat", "Lama Sewa", "Total Biaya"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablePenyewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePenyewaanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePenyewaan);

        jLabel6.setText("Alat Berat");

        jLabel7.setText("Nama");

        jLabel8.setText("Lama Sewa");

        jButtonTambahPenyewaan.setText("Tambah");
        jButtonTambahPenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahPenyewaanActionPerformed(evt);
            }
        });

        jButtonUpdatePenyewaan.setText("Update");
        jButtonUpdatePenyewaan.setToolTipText("");
        jButtonUpdatePenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatePenyewaanActionPerformed(evt);
            }
        });

        jButtonBatalPenyewaan.setText("Batal");
        jButtonBatalPenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalPenyewaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtNama1)
                            .addComponent(jTxtHarga1)
                            .addComponent(jCmbPilihAlatBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonTambahPenyewaan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonUpdatePenyewaan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBatalPenyewaan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jCmbPilihAlatBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTxtNama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBatalPenyewaan)
                    .addComponent(jButtonUpdatePenyewaan)
                    .addComponent(jButtonTambahPenyewaan))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jButtonDeletePenyewaan.setText("Delete");
        jButtonDeletePenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePenyewaanActionPerformed(evt);
            }
        });

        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPenyewaanLayout = new javax.swing.GroupLayout(jPanelPenyewaan);
        jPanelPenyewaan.setLayout(jPanelPenyewaanLayout);
        jPanelPenyewaanLayout.setHorizontalGroup(
            jPanelPenyewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPenyewaanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelPenyewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPenyewaanLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                        .addComponent(jButtonDeletePenyewaan))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPenyewaanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCari, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanelPenyewaanLayout.setVerticalGroup(
            jPanelPenyewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPenyewaanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelPenyewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPenyewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeletePenyewaan))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Penyewaan", jPanelPenyewaan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmbJenisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbJenisItemStateChanged
        String selected = (String) jCmbJenis.getSelectedItem();

        if (selected != null) {
            labelPropTambahan.setVisible(true);
            jTxtTambahan.setVisible(true);

            switch(selected) {
                case "Bulldozer":
                labelPropTambahan.setText("Tipe Blade");
                jTxtTambahan.setToolTipText("Contoh: Lurus, Melengkung");
                break;
                case "Crane":
                labelPropTambahan.setText("Kapasitas Angkat (Ton)");
                jTxtTambahan.setToolTipText("Contoh: 50, 100, 150");
                break;
                case "Excavator":
                labelPropTambahan.setText("Kapasitas Bucket (m³)");
                jTxtTambahan.setToolTipText("Contoh: 0.5, 1.0, 1.5");
                break;
            }
        }
    }//GEN-LAST:event_jCmbJenisItemStateChanged

    // TAMBAH
    private void jButtonTambahAlatBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahAlatBeratActionPerformed
        String jenis = (String) jCmbJenis.getSelectedItem();
        String nama = jTxtNama.getText();
        String hargaText = jTxtHarga.getText();
        String tambahan = jTxtTambahan.getText();

        try {
            alatBeratService.tambahAlatBerat(jenis, nama, hargaText, tambahan);
            
            refreshAlatTable();
            clearAlatForm();
            JOptionPane.showMessageDialog(this, "Alat berat berhasil ditambahkan!");
            
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonTambahAlatBeratActionPerformed

    // UPDATE
    private void jButtonUpdateAlatBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateAlatBeratActionPerformed
        int row = jTableAlatBerat.getSelectedRow();
        if (row < 0 || row >= alatBeratService.getSemuaAlat().size()) {
            JOptionPane.showMessageDialog(this, "Pilih data pada tabel terlebih dahulu.");
            return;
        }

        String jenis = (String) jCmbJenis.getSelectedItem();
        String nama = jTxtNama.getText();
        String hargaText = jTxtHarga.getText();
        String tambahan = jTxtTambahan.getText();

        try {
            alatBeratService.updateAlatBerat(row, jenis, nama, hargaText, tambahan);
            
            refreshAlatTable();
            clearAlatForm();
            jTableAlatBerat.clearSelection();
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
            
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonUpdateAlatBeratActionPerformed

    // LOAD DATA TO FORM
    private void jTableAlatBeratMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlatBeratMouseClicked
        // TODO add your handling code here:
        loadAlatToForm();
    }//GEN-LAST:event_jTableAlatBeratMouseClicked

    // DELETE
    private void jButtonDeleteAlatBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteAlatBeratActionPerformed
        int row = jTableAlatBerat.getSelectedRow();
        if (row < 0 || row >= alatBeratService.getSemuaAlat().size()) {
            JOptionPane.showMessageDialog(this, "Pilih data pada tabel terlebih dahulu.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Hapus data alat berat yang dipilih?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        alatBeratService.hapusAlatBerat(row);

        refreshAlatTable();
        jTableAlatBerat.clearSelection();
        clearAlatForm();
    }//GEN-LAST:event_jButtonDeleteAlatBeratActionPerformed

    // BATAL / CLEAR FORM
    private void jButtonBatalAlatBeratMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBatalAlatBeratMouseClicked
        // TODO add your handling code here:
        jTableAlatBerat.clearSelection();
        clearAlatForm();
    }//GEN-LAST:event_jButtonBatalAlatBeratMouseClicked

    private void jButtonTambahPenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahPenyewaanActionPerformed
        // TODO add your handling code here:
        int alatIndex = jCmbPilihAlatBerat.getSelectedIndex();
        String namaPenyewa = jTxtNama1.getText().trim();
        String lamaSewaText = jTxtHarga1.getText().trim();

        if (alatIndex < 0) {
            JOptionPane.showMessageDialog(this, "Pilih Alat Berat terlebih dahulu.");
            return;
        }
        if (namaPenyewa.isEmpty() || lamaSewaText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Penyewa dan Lama Sewa wajib diisi.");
            return;
        }

        try {
            int lamaSewa = Integer.parseInt(lamaSewaText);
            if (lamaSewa <= 0) {
                JOptionPane.showMessageDialog(this, "Lama sewa harus lebih dari 0 hari.");
                return;
            }
            
            AlatBerat alatDipilih = alatBeratService.getByIndex(alatIndex);
            Penyewaan penyewaan = new Penyewaan(nextPenyewaanId(), namaPenyewa, alatDipilih, lamaSewa);
            
            penyewaanList.add(penyewaan);
            refreshPenyewaanTable();
            clearPenyewaanForm();
            JOptionPane.showMessageDialog(this, "Penyewaan berhasil ditambahkan!");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lama sewa harus berupa angka.");
        }
    }//GEN-LAST:event_jButtonTambahPenyewaanActionPerformed

    private void jButtonUpdatePenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatePenyewaanActionPerformed
        // TODO add your handling code here:
        int row = jTablePenyewaan.getSelectedRow();
        if (row < 0 || row >= penyewaanList.size()) {
            JOptionPane.showMessageDialog(this, "Pilih data penyewaan pada tabel terlebih dahulu.");
            return;
        }

        String namaPenyewa = jTxtNama1.getText().trim();
        String lamaSewaText = jTxtHarga1.getText().trim();

        if (namaPenyewa.isEmpty() || lamaSewaText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Penyewa dan Lama Sewa wajib diisi.");
            return;
        }

        try {
            int lamaSewa = Integer.parseInt(lamaSewaText);
            
            Penyewaan lama = penyewaanList.get(row);
            Penyewaan update = new Penyewaan(lama.getIdPenyewaan(), namaPenyewa, lama.getAlatBerat(), lamaSewa);
            
            penyewaanList.set(row, update);
            refreshPenyewaanTable();
            clearPenyewaanForm();
            jTablePenyewaan.clearSelection();
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lama sewa harus berupa angka.");
        }
    }//GEN-LAST:event_jButtonUpdatePenyewaanActionPerformed

    private void jButtonBatalPenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalPenyewaanActionPerformed
        // TODO add your handling code here:
        clearPenyewaanForm();
        jTablePenyewaan.clearSelection();
        refreshPenyewaanTable();
    }//GEN-LAST:event_jButtonBatalPenyewaanActionPerformed

    private void jButtonDeletePenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePenyewaanActionPerformed
        // TODO add your handling code here:
        int row = jTablePenyewaan.getSelectedRow();
        if (row < 0 || row >= penyewaanList.size()) {
            JOptionPane.showMessageDialog(this, "Pilih data penyewaan pada tabel terlebih dahulu.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Hapus data penyewaan ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            penyewaanList.remove(row);
            refreshPenyewaanTable();
            clearPenyewaanForm();
        }
    }//GEN-LAST:event_jButtonDeletePenyewaanActionPerformed

    private void jTablePenyewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePenyewaanMouseClicked
        // TODO add your handling code here:
        int row = jTablePenyewaan.getSelectedRow();
        if (row < 0 || row >= penyewaanList.size()) return;

        Penyewaan p = penyewaanList.get(row);
        
        List<AlatBerat> alatList = alatBeratService.getSemuaAlat();
        
        for (int i = 0; i < alatList.size(); i++) {
            if (alatList.get(i).getIdAlat().equals(p.getAlatBerat().getIdAlat())) {
                jCmbPilihAlatBerat.setSelectedIndex(i);
                break;
            }
        }
        
        jCmbPilihAlatBerat.setEnabled(false);
        jTxtNama1.setText(p.getNamaPenyewa());
        jTxtHarga1.setText(String.valueOf(p.getLamaSewa()));
    }//GEN-LAST:event_jTablePenyewaanMouseClicked

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        String keyword = jTextCari.getText().trim().toLowerCase();
        
        if (keyword.isEmpty()) {
            refreshPenyewaanTable();
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTablePenyewaan.getModel();
        model.setRowCount(0);
        
        boolean isFound = false;

        for (Penyewaan p : penyewaanList) {
            if (p.getNamaPenyewa().toLowerCase().contains(keyword) || 
                p.getIdPenyewaan().toLowerCase().contains(keyword)) {
                
                model.addRow(new Object[]{
                    p.getIdPenyewaan(),
                    p.getNamaPenyewa(),
                    p.getAlatBerat().getNamaAlat(),
                    p.getLamaSewa(),
                    p.getTotalBiaya()
                });
                isFound = true;
            }
        }

        if (!isFound) {
            JOptionPane.showMessageDialog(this, "Data dengan kata kunci '" + keyword + "' tidak ditemukan.");
            refreshPenyewaanTable();
            jTextCari.setText("");
        }
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void refreshAlatTable() {
        DefaultTableModel model = (DefaultTableModel) jTableAlatBerat.getModel();
        model.setRowCount(0);

        for (AlatBerat alat : alatBeratService.getSemuaAlat()) {
            String jenis;
            String spesifikasi = "-";
            
            if (alat instanceof Bulldozer) {
                jenis = "Bulldozer";
                Bulldozer bulldozer = (Bulldozer) alat;
                spesifikasi = "Blade: " + bulldozer.getTipeBlade();
            } else if (alat instanceof Crane) {
                jenis = "Crane";
                Crane crane = (Crane) alat;
                spesifikasi = "Kapasitas: " + crane.getKapasitasAngkat() + " Ton";
            } else if (alat instanceof Excavator) {
                jenis = "Excavator";
                Excavator excavator = (Excavator) alat;
                spesifikasi = "Kapasitas: " + excavator.getKapasitasBucket() + " m³";
            } else {
                jenis = "-";
            }

            model.addRow(new Object[] {
                alat.getIdAlat(),
                jenis,
                alat.getNamaAlat(),
                (int) alat.getHargaSewaPerHari(),
                spesifikasi
            });
        }
        refreshComboBoxAlat();
    }

    private void clearAlatForm() {
        jCmbJenis.setSelectedIndex(-1);
        jCmbJenis.setEnabled(true);
        jTxtNama.setText("");
        jTxtHarga.setText("");
        jTxtTambahan.setText("");
        labelPropTambahan.setVisible(false);
        jTxtTambahan.setVisible(false);
    }

    private void loadAlatToForm() {
        int row = jTableAlatBerat.getSelectedRow();
        if (row < 0 || row >= alatBeratService.getSemuaAlat().size()) {
            return;
        }

        // Ambil alat dari service
        AlatBerat alat = alatBeratService.getByIndex(row);
        if (alat instanceof Bulldozer) {
            Bulldozer bulldozer = (Bulldozer) alat;
            jCmbJenis.setSelectedItem("Bulldozer");
            jTxtTambahan.setText(bulldozer.getTipeBlade());
        } else if (alat instanceof Crane) {
            Crane crane = (Crane) alat;
            jCmbJenis.setSelectedItem("Crane");
            jTxtTambahan.setText(String.valueOf(crane.getKapasitasAngkat()));
        } else if (alat instanceof Excavator) {
            Excavator excavator = (Excavator) alat;
            jCmbJenis.setSelectedItem("Excavator");
            jTxtTambahan.setText(String.valueOf(excavator.getKapasitasBucket()));
        }

        jCmbJenis.setEnabled(false);

        jTxtNama.setText(alat.getNamaAlat());
        jTxtHarga.setText(String.valueOf(alat.getHargaSewaPerHari()));
    }
    
    private void refreshComboBoxAlat() {
        jCmbPilihAlatBerat.removeAllItems();
        for (AlatBerat alat : alatBeratService.getSemuaAlat()) {
            jCmbPilihAlatBerat.addItem(alat.getIdAlat() + " - " + alat.getNamaAlat());
        }
    }
    
    private void refreshPenyewaanTable() {
        DefaultTableModel model = (DefaultTableModel) jTablePenyewaan.getModel();
        model.setRowCount(0);

        for (Penyewaan p : penyewaanList) {
            model.addRow(new Object[]{
                p.getIdPenyewaan(),
                p.getNamaPenyewa(),
                p.getAlatBerat().getNamaAlat(),
                p.getLamaSewa(),
                p.getTotalBiaya()
            });
        }
    }
    
    private void clearPenyewaanForm() {
        jCmbPilihAlatBerat.setSelectedIndex(-1);
        jCmbPilihAlatBerat.setEnabled(true);
        jTxtNama1.setText("");
        jTxtHarga1.setText("");
    }
    
    private String nextPenyewaanId() {
        int max = 0;
        for (Penyewaan p : penyewaanList) {
            String id = p.getIdPenyewaan();
            if (id != null && id.startsWith("SEWA")) {
                try {
                    int value = Integer.parseInt(id.substring(4));
                    if (value > max) max = value;
                } catch (NumberFormatException ex) {}
            }
        }
        return "SEWA" + (max + 1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatalAlatBerat;
    private javax.swing.JButton jButtonBatalPenyewaan;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonDeleteAlatBerat;
    private javax.swing.JButton jButtonDeletePenyewaan;
    private javax.swing.JButton jButtonTambahAlatBerat;
    private javax.swing.JButton jButtonTambahPenyewaan;
    private javax.swing.JButton jButtonUpdateAlatBerat;
    private javax.swing.JButton jButtonUpdatePenyewaan;
    private javax.swing.JComboBox<String> jCmbJenis;
    private javax.swing.JComboBox<String> jCmbPilihAlatBerat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAlatBerat;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelPenyewaan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTableAlatBerat;
    private javax.swing.JTable jTablePenyewaan;
    private javax.swing.JTextField jTextCari;
    private javax.swing.JTextField jTxtHarga;
    private javax.swing.JTextField jTxtHarga1;
    private javax.swing.JTextField jTxtNama;
    private javax.swing.JTextField jTxtNama1;
    private javax.swing.JTextField jTxtTambahan;
    private javax.swing.JLabel labelPropTambahan;
    // End of variables declaration//GEN-END:variables
}
